# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import remote_types_pb2 as remote__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='remote.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cremote.proto\x1a\x12remote_types.proto2\xf0\x01\n\x06Remote\x12\x38\n\x07\x41\x64\x64\x43url\x12\x16.remote.AddCurlRequest\x1a\x15.remote.AddCurlResult\x12\x38\n\x07\x43urlRes\x12\x16.remote.CurlResRequest\x1a\x15.remote.CurlResResult\x12\x38\n\x07\x41\x64\x64Ping\x12\x16.remote.AddPingRequest\x1a\x15.remote.AddPingResult\x12\x38\n\x07PingRes\x12\x16.remote.PingResRequest\x1a\x15.remote.PingResResultb\x06proto3')
  ,
  dependencies=[remote__types__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_REMOTE = _descriptor.ServiceDescriptor(
  name='Remote',
  full_name='Remote',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=37,
  serialized_end=277,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddCurl',
    full_name='Remote.AddCurl',
    index=0,
    containing_service=None,
    input_type=remote__types__pb2._ADDCURLREQUEST,
    output_type=remote__types__pb2._ADDCURLRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CurlRes',
    full_name='Remote.CurlRes',
    index=1,
    containing_service=None,
    input_type=remote__types__pb2._CURLRESREQUEST,
    output_type=remote__types__pb2._CURLRESRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddPing',
    full_name='Remote.AddPing',
    index=2,
    containing_service=None,
    input_type=remote__types__pb2._ADDPINGREQUEST,
    output_type=remote__types__pb2._ADDPINGRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PingRes',
    full_name='Remote.PingRes',
    index=3,
    containing_service=None,
    input_type=remote__types__pb2._PINGRESREQUEST,
    output_type=remote__types__pb2._PINGRESRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REMOTE)

DESCRIPTOR.services_by_name['Remote'] = _REMOTE

# @@protoc_insertion_point(module_scope)
